#:kivy 1.0.9
<GameWidget>:
    canvas:
        Rectangle:
            source: './assets/background.jpg'
            pos: self.pos
            size: self.size
        Rectangle:
            source: './assets/leaf.png'
            size: 150, 150
            pos: self.width / 4 - 20, self.top - 600

        Rectangle:
            source: './assets/leaf.png'
            size: 150, 150
            pos: self.width * 3 / 4 - 20, self.top - 600


